name: meep_scanner
on: [push]

jobs:
  meep_scan:
    runs-on: ubuntu-latest
    name: meep_scanner
    steps:
    - uses: moreeyesplz/meep_scanner@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
